import { useEffect, useState } from 'react';
import { buildReportModel } from '../report/reportBuilder';
import { AlertCircle, Printer } from 'lucide-react';
import {
  renderCoverPage,
  renderExecutiveSummary,
  renderStrategySection,
  renderArchitectureSection,
  renderBuildSection,
  renderPocSection,
  renderCostsSection,
  renderTestingSection,
  renderOperateSection,
  renderReportingSection,
  renderAppendices
} from '../report/renderSections';

export function ReportPrintView() {
  const [scenarioId, setScenarioId] = useState<string | null>(null);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const id = params.get('scenarioId');
    if (id) {
      setScenarioId(id);
    }
  }, []);

  if (!scenarioId) {
    return <div className="p-8">Loading...</div>;
  }

  const report = buildReportModel(scenarioId);

  if (!report) {
    return (
      <div className="p-8 text-center text-gray-500 dark:text-slate-400">
        <AlertCircle className="w-12 h-12 mx-auto mb-4 text-red-500" />
        <h3 className="text-lg font-medium">Unable to generate report</h3>
        <p>Could not find scenario data for ID: {scenarioId}</p>
      </div>
    );
  }

  return (
    <div className="print-container max-w-[210mm] mx-auto bg-white dark:bg-slate-800 p-[20mm] min-h-screen">
      {renderCoverPage(report)}
      {renderExecutiveSummary(report)}
      <div className="page-break" />
      {renderStrategySection(report)}
      <div className="page-break" />
      {renderArchitectureSection(report)}
      <div className="page-break" />
      {renderBuildSection(report)}
      <div className="page-break" />
      {renderPocSection(report)}
      <div className="page-break" />
      {renderCostsSection(report)}
      <div className="page-break" />
      {renderTestingSection(report)}
      <div className="page-break" />
      {renderOperateSection(report)}
      <div className="page-break" />
      {renderReportingSection(report)}
      <div className="page-break" />
      {renderAppendices(report)}

      {/* Footer */}
      <footer className="mt-12 pt-4 border-t border-gray-200 dark:border-slate-700 text-center text-xs text-gray-500 dark:text-slate-400 print:hidden">
        <p>Generated by Agent Sizing Workshop</p>
      </footer>

      {/* Print Button (Screen Only) */}
      <div className="fixed bottom-8 right-8 print:hidden">
        <button 
          onClick={() => window.print()}
          className="bg-blue-600 dark:bg-blue-500 text-white px-6 py-3 rounded-full shadow-lg hover:bg-blue-700 dark:hover:bg-blue-600 font-medium flex items-center gap-2 transition-colors"
        >
          <Printer className="w-5 h-5" />
          Print Report
        </button>
      </div>
    </div>
  );
}
